# -*- coding: utf-8 -*-
"""Personal Project - Data Analysis of Azduna Job Listings

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oyus0_wa75ReS48MiAg0xwXQXOSF0tYL
"""

import csv
import os

FilePath = os.path.join("/content/adzuna_global_job_listings_2025.csv") #You may need to re-upload this file at some point, google colab is weird about it

"""Question: How significantly do seniority keywords (e.g., "Senior", "Principal", "Lead") in job titles impact the offered salary compared to standard or junior roles?

1.   List item
2.   List item


"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.ticker import FuncFormatter

df = pd.read_csv(FilePath)

df['avg_salary'] = (df['salary_min'] + df['salary_max']) / 2

def categorize_seniority(title):
    title_lower = str(title).lower()
    if any(x in title_lower for x in ['senior', 'sr.', 'sr ', 'principal', 'lead', 'manager', 'director']):
        return 'Senior/Lead'
    elif any(x in title_lower for x in ['junior', 'jr.', 'jr ', 'associate', 'entry', 'intern']):
        return 'Junior/Entry'
    else:
        return 'Mid-Level/Standard'

df['Seniority_Level'] = df['title'].apply(categorize_seniority)


order = ['Junior/Entry', 'Mid-Level/Standard', 'Senior/Lead']

plt.figure(figsize=(10, 6))
sns.set_theme(style="whitegrid")

graph = sns.boxplot(
    x='Seniority_Level',
    y='avg_salary',
    data=df,
    order=order,
    hue='Seniority_Level', # Added to address FutureWarning
    palette="viridis",
    legend=False, # Added to address FutureWarning
    showfliers=False # Optional: Turn to True to see outlier dots
)

plt.title('Impact of Job Title Seniority on Salary Distribution', fontsize=16)
plt.xlabel('Seniority Level (Derived from Title)', fontsize=12)
plt.ylabel('Average Yearly Salary ($)', fontsize=12)

# Format y-axis to show dollars (e.g., $100,000) using FuncFormatter
def dollar_formatter(x, pos):
    return '${:,.0f}'.format(x)

formatter = FuncFormatter(dollar_formatter)
plt.gca().yaxis.set_major_formatter(formatter)

plt.show()

"""Seniority keywords have a statistically significant and substantial impact on offered salaries. The data indicates a clear "step-ladder" effect where adding seniority keywords correlates with distinct jumps in pay.

Key Findings:

- The "Senior Premium" is Huge: According to your boxplot, the median salary for "Senior/Lead" roles is approximately $115,000, whereas "Mid-Level/Standard" roles sit around $80,000. This suggests that simply earning a "Senior" title can correlate with a 44% increase in base salary.

- "Principal" Drives the Top End: Looking at the raw data in your spreadsheet, specific keywords like "Principal" push salaries even higher than the standard "Senior" band. For example, "Principal Software Development Engineer" roles at Oracle consistently appear in the $170,000 - $220,000 range, significantly outperforming the general "Senior" average.

- Junior Roles have a Lower Ceiling: "Junior/Entry" roles have a much tighter salary range, with a median near $65,000 and very few outliers reaching above $100k.

Conclusion: You can conclude that job title keywords are a highly effective predictor of salary. The jump from "Mid-Level" to "Senior" is actually larger in dollar terms than the jump from "Junior" to "Mid-Level," indicating that the highest financial returns in a career come from breaking into that "Senior/Lead" bracket.
"""